# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 22:29
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Autor(a)')),
            ],
            options={
                'verbose_name': 'Autor(a)',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200)),
                ('activated', models.BooleanField(default=True, verbose_name='Ativo')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1564), django.core.validators.MaxValueValidator(2017)], verbose_name='Ano')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Publicação')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sys.Author', verbose_name='Autor(a)')),
            ],
            options={
                'verbose_name_plural': 'Livros',
                'verbose_name': 'Livro',
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sys.Book', verbose_name='Livro')),
            ],
            options={
                'verbose_name_plural': 'Exemplares',
                'verbose_name': 'Exemplar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='HistoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(verbose_name='Emprestado em')),
                ('date_due', models.DateField(verbose_name='À ser entregue em')),
                ('date_returned', models.DateField(blank=True, null=True, verbose_name='Entregue em')),
                ('fine', models.SmallIntegerField(default=0, verbose_name='Multa total')),
                ('daily_fine', models.SmallIntegerField(default=0, verbose_name='Multa diária')),
                ('is_fine_paid', models.NullBooleanField(default=False, verbose_name='Multa paga?')),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sys.BookItem', verbose_name='Exemplar')),
            ],
            options={
                'verbose_name_plural': 'Empréstimos',
                'verbose_name': 'Empréstimo',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Editora')),
            ],
            options={
                'verbose_name': 'Editora',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Usuári@',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='historyitem',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sys.Reader', verbose_name='Leitor(a)'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='library_sys.Category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sys.Publisher', verbose_name='Editora'),
        ),
    ]
