# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import library_sys.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0004_auto_20170317_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_height', null=True, upload_to=library_sys.models.Book.get_upload_to_image, verbose_name='capa', width_field='cover_width'),
        ),
    ]
