# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import library_sys.models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0005_auto_20170317_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, help_text='Selecione o arquivo do livro\n                             para download.', null=True, upload_to=library_sys.models.Book.get_upload_to_file, verbose_name='arquivo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='library_sys.Category', verbose_name='categorias'),
        ),
    ]
