# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import library_sys.models
import library_sys.validators


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0007_auto_20170317_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, height_field='cover_height', help_text='Selecione a imagem de capa\n                               do livro, normalmente nos formatos\n                               jpg, png, gif, etc.', null=True, upload_to=library_sys.models.Book.get_upload_to_image, validators=library_sys.validators.FileValidator, verbose_name='capa', width_field='cover_width'),
        ),
    ]
