# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0012_auto_20170320_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_item_available',
        ),
        migrations.AddField(
            model_name='book',
            name='book_item_unavailable',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='total de exemplares indisponíveis'),
        ),
    ]
