# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0013_auto_20170321_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponível'),
        ),
    ]
