# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0015_auto_20170321_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookitem',
            options={'ordering': ['book__title'], 'verbose_name': 'exemplar', 'verbose_name_plural': 'exemplares'},
        ),
        migrations.AlterModelOptions(
            name='historyitem',
            options={'ordering': ['-date_taken'], 'verbose_name': 'empréstimo', 'verbose_name_plural': 'empréstimos'},
        ),
        migrations.AddField(
            model_name='bookitem',
            name='last_date_due',
            field=models.DateField(blank=True, null=True, verbose_name='ultima previsão de entrega'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='last_date_returned',
            field=models.DateField(blank=True, null=True, verbose_name='entregue em'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='last_date_taken',
            field=models.DateField(blank=True, null=True, verbose_name='data ultimo empréstimo'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='last_history_item_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ultimo empréstimo'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='last_reader_id',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='ultimo leitor(a)'),
        ),
    ]
