# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 16:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0016_auto_20170327_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='observações'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_item_total',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total de exemplares'),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='last_date_due',
            field=models.DateField(blank=True, null=True, verbose_name='previsão de entrega'),
        ),
    ]
