# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_sys', '0017_auto_20170328_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookitem',
            options={'ordering': ['book__title', 'book__author__name'], 'verbose_name': 'exemplar', 'verbose_name_plural': 'exemplares'},
        ),
    ]
